--drop table HISTORICO_ALIMENTACION ;
--
--CREATE TABLE historico_alimentacion (
--    id_historico    NUMBER
--        GENERATED BY DEFAULT AS IDENTITY
--    PRIMARY KEY,
--    idanimal        NUMBER,
--    fecha_cambio    DATE DEFAULT sysdate,
--    id_alim_antigua NUMBER,
--    id_alim_nueva   NUMBER,
--    usuario         VARCHAR2(50) -- Usuario que realizó el cambio
--);


--He preferido usar el when xk me parece mucho más legible a la hora de declararlo (aunque no hay que poner los :)
--por otro lado, al parecer is distinct from es para versiones de oracle más modernas que la que tengo instalada

SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER trg_auditar_alimentacion AFTER
    UPDATE OF idalimentacion_esp ON animal
    FOR EACH ROW
    -- no funciona en 21c: WHEN (new.idalimentacion_esp IS DISTINCT FROM old.idalimentacion_esp)
    WHEN (NVL(new.idalimentacion_esp, -1) != NVL(old.idalimentacion_esp, -1)) 
BEGIN
    INSERT INTO historico_alimentacion (
        idanimal,
        fecha_cambio,
        id_alim_antigua,
        id_alim_nueva,
        usuario
    ) VALUES ( :new.idanimal,
               sysdate,
               :old.idalimentacion_esp,
               :new.idalimentacion_esp,
               user );

    dbms_output.put_line('Trigger trg_auditar_alimentacion disparado');
END trg_auditar_alimentacion;
/

--UPDATE animal
--SET
--    idalimentacion_esp = 3
--WHERE
--    idanimal = 6;
--
--
--COMMIT;
