CREATE USER tarea_ud6 IDENTIFIED BY 1234
QUOTA UNLIMITED ON USERS;

GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE SEQUENCE,
    CREATE PROCEDURE,
    CREATE TRIGGER
TO tarea_ud6;
