CREATE USER JUAN_CRUZ_GARRIDO_SUSO IDENTIFIED BY 1234
QUOTA UNLIMITED ON USERS;

GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE SEQUENCE,
    CREATE PROCEDURE,
    CREATE TRIGGER
TO JUAN_CRUZ_GARRIDO_SUSO;

-- XEPDB1

CREATE USER INVITADO IDENTIFIED BY 1234;
GRANT CREATE SESSION TO INVITADO