package ej15_EscRaton;


import java.awt.event.* ;

public class miMarcoRaton extends javax.swing.JFrame {
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    /** Construcor: crea nuevo marco miMarcoRaton */
    public miMarcoRaton() {
        initComponents();
        
        // Crear el objeto oyente de ratón
        OyenteRaton oyenteRat = new OyenteRaton() ;

        // Registrar el oyente en el botón de Aceptar
        jButton1.addMouseListener(oyenteRat);
        // Registrar el oyente en el botón de Cancelar
        jButton2.addMouseListener(oyenteRat);
    }

    // Implementar la clase oyente que implemente el interface MouseListener
    // Se deja en blanco el cuerpo de mouseEntered y de mouseExited, ya que
    // no nos interesan en este ejemplo. Cuando se desea escuchar algún
    // tipo de evento, de deben implementar todos los métodos del interface
    // para que la clase no tenga que ser definida como abstracta
    class OyenteRaton implements MouseListener{
        // Gestionar evento de pulsación de cualquier tecla
        public void mousePressed(MouseEvent e) {
            escribir("Botón de ratón pulsado", e) ;      
        }
        public void mouseReleased(MouseEvent e) {
            escribir("Botón de ratón liberado", e);
        }
        public void mouseEntered(MouseEvent e) {
        }
        public void mouseExited(MouseEvent e) {
        }
        public void mouseClicked(MouseEvent e) {
            escribir("Click en el botón del ratón", e);
        }

        void escribir(String eventDescription, MouseEvent e) {
            // Escribir en el área de texto la descripción  que
            // se recibe como parámetro
            jTextArea1.append(eventDescription + ".\n");

            // Comprobamos cuál de los dos botones es y lo escribimos
            if (e.getComponent().getName().equals(jButton1.getName()) )
               jTextArea1.append("Es el botón Aceptar.\n");
            else
               jTextArea1.append("Es el botón Cancelar.\n");
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Aceptar");
        jButton1.setName("Aceptar"); // NOI18N

        jButton2.setText("Cancelar");
        jButton2.setName("Cancelar"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new miMarcoRaton().setVisible(true);
            }
        });
    }

    

}
